### ISSUE TITLE
Exception parsing dates

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-toolkit#21] opened 2019-11-05 21:58 UTC
Analyzing some [GNOME mailing lists](https://gitlab.com/jsmanrique/grimoirelab-demo-for-gnome/blob/master/projects.json) I am getting this exception message in mordred logs:

```
mordred_1        | --- Logging error ---
mordred_1        | Traceback (most recent call last):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoirelab_toolkit/datetime.py", line 143, in str_to_datetime
mordred_1        |     raise e
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoirelab_toolkit/datetime.py", line 131, in str_to_datetime
mordred_1        |     dt = parse_datetime(ts)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoirelab_toolkit/datetime.py", line 113, in parse_datetime
mordred_1        |     dt = dateutil.parser.parse(ts)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 1358, in parse
mordred_1        |     return DEFAULTPARSER.parse(timestr, **kwargs)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 649, in parse
mordred_1        |     raise ValueError("Unknown string format:", timestr)
mordred_1        | ValueError: ('Unknown string format:', 'Sun, 24 Feb 02 04:31:03 \udcb4\udceb\udcc7\udcd1\udcb9\udcce\udcb1\udcb9 \udcc7\udca5\udcc1\udcd8\udcbd\udcc3')
mordred_1        | 
mordred_1        | During handling of the above exception, another exception occurred:
mordred_1        | 
mordred_1        | Traceback (most recent call last):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/mbox.py", line 275, in _validate_message
mordred_1        |     str_to_datetime(message[self.DATE_FIELD])
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoirelab_toolkit/datetime.py", line 148, in str_to_datetime
mordred_1        |     raise InvalidDateError(date=str(ts))
mordred_1        | grimoirelab_toolkit.datetime.InvalidDateError: Sun, 24 Feb 02 04:31:03 \udcb4\udceb\udcc7\udcd1\udcb9\udcce\udcb1\udcb9 \udcc7\udca5\udcc1\udcd8\udcbd\udcc3 is not a valid date
mordred_1        | 
mordred_1        | During handling of the above exception, another exception occurred:
mordred_1        | 
mordred_1        | Traceback (most recent call last):
mordred_1        |   File "/usr/lib/python3.5/logging/__init__.py", line 983, in emit
mordred_1        |     stream.write(msg)
mordred_1        | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb4' in position 103: surrogates not allowed
mordred_1        | Call stack:
mordred_1        |   File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
mordred_1        |     self._bootstrap_inner()
mordred_1        |   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
mordred_1        |     self.run()
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/sirmordred/task_manager.py", line 97, in run
mordred_1        |     task.execute()
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/sirmordred/task_collection.py", line 138, in execute
mordred_1        |     repo_labels=repo_labels)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 228, in feed_backend
mordred_1        |     ocean_backend.feed(**params)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 230, in feed
mordred_1        |     self.feed_items(items)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 246, in feed_items
mordred_1        |     for item in items:
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 215, in fetch
mordred_1        |     for item in self.fetch_items(category, **kwargs):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/pipermail.py", line 108, in fetch_items
mordred_1        |     for message in messages:
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/mbox.py", line 204, in _fetch_and_parse_messages
mordred_1        |     if not self._validate_message(message):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/mbox.py", line 278, in _validate_message
mordred_1        |     message[self.DATE_FIELD], message['unixfrom'])
mordred_1        | Message: 'Invalid date %s in message %s; ignoring'
mordred_1        | Arguments: ('Sun, 24 Feb 02 04:31:03 \udcb4\udceb\udcc7\udcd1\udcb9\udcce\udcb1\udcb9 \udcc7\udca5\udcc1\udcd8\udcbd\udcc3', 'nautilus-list-admin@mx.eazel.com Sat Feb 23 11:52:05 2002')
mordred_1        | --- Logging error ---
mordred_1        | Traceback (most recent call last):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoirelab_toolkit/datetime.py", line 143, in str_to_datetime
mordred_1        |     raise e
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoirelab_toolkit/datetime.py", line 131, in str_to_datetime
mordred_1        |     dt = parse_datetime(ts)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoirelab_toolkit/datetime.py", line 113, in parse_datetime
mordred_1        |     dt = dateutil.parser.parse(ts)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 1358, in parse
mordred_1        |     return DEFAULTPARSER.parse(timestr, **kwargs)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/dateutil/parser/_parser.py", line 649, in parse
mordred_1        |     raise ValueError("Unknown string format:", timestr)
mordred_1        | ValueError: ('Unknown string format:', 'Sun, 24 Feb 02 04:31:03 \udcb4\udceb\udcc7\udcd1\udcb9\udcce\udcb1\udcb9 \udcc7\udca5\udcc1\udcd8\udcbd\udcc3')
mordred_1        | 
mordred_1        | During handling of the above exception, another exception occurred:
mordred_1        | 
mordred_1        | Traceback (most recent call last):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/mbox.py", line 275, in _validate_message
mordred_1        |     str_to_datetime(message[self.DATE_FIELD])
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoirelab_toolkit/datetime.py", line 148, in str_to_datetime
mordred_1        |     raise InvalidDateError(date=str(ts))
mordred_1        | grimoirelab_toolkit.datetime.InvalidDateError: Sun, 24 Feb 02 04:31:03 \udcb4\udceb\udcc7\udcd1\udcb9\udcce\udcb1\udcb9 \udcc7\udca5\udcc1\udcd8\udcbd\udcc3 is not a valid date
mordred_1        | 
mordred_1        | During handling of the above exception, another exception occurred:
mordred_1        | 
mordred_1        | Traceback (most recent call last):
mordred_1        |   File "/usr/lib/python3.5/logging/__init__.py", line 983, in emit
mordred_1        |     stream.write(msg)
mordred_1        | UnicodeEncodeError: 'utf-8' codec can't encode character '\udcb4' in position 103: surrogates not allowed
mordred_1        | Call stack:
mordred_1        |   File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
mordred_1        |     self._bootstrap_inner()
mordred_1        |   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
mordred_1        |     self.run()
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/sirmordred/task_manager.py", line 97, in run
mordred_1        |     task.execute()
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/sirmordred/task_collection.py", line 138, in execute
mordred_1        |     repo_labels=repo_labels)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 228, in feed_backend
mordred_1        |     ocean_backend.feed(**params)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 230, in feed
mordred_1        |     self.feed_items(items)
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/raw/elastic.py", line 246, in feed_items
mordred_1        |     for item in items:
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 215, in fetch
mordred_1        |     for item in self.fetch_items(category, **kwargs):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/pipermail.py", line 108, in fetch_items
mordred_1        |     for message in messages:
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/mbox.py", line 204, in _fetch_and_parse_messages
mordred_1        |     if not self._validate_message(message):
mordred_1        |   File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/mbox.py", line 278, in _validate_message
mordred_1        |     message[self.DATE_FIELD], message['unixfrom'])
mordred_1        | Message: 'Invalid date %s in message %s; ignoring'
mordred_1        | Arguments: ('Sun, 24 Feb 02 04:31:03 \udcb4\udceb\udcc7\udcd1\udcb9\udcce\udcb1\udcb9 \udcc7\udca5\udcc1\udcd8\udcbd\udcc3', 'nautilus-list-admin@mx.eazel.com Sat Feb 23 11:52:05 2002')
```

Probably it's happening in [nautilus mailing list](https://mail.gnome.org/archives/nautilus-list/), but I cannot ensure it.

And reading the log, I am not 100% if it's a Perceval, GELK, or grimoirelab-toolkit issue... Any help?

**Comment by valeriocos** [comment] 2019-11-12 08:31
I'm not able to reproduce the error using the current [HEAD](https://github.com/chaoss/grimoirelab-toolkit/commit/ba1f9318228a79f393a5edea1a33efbff341ca85)

**Comment by sduenas** [comment] 2019-11-13 07:22
It's a unicode error. I don't think we can do much there. If you were unable to reproduce it, let's close it.

**Closed** 2019-11-13 07:26 UTC
